services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www  # Ensure this mounts the Laravel project
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flowTask
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www  # Mount Laravel project
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: